### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by openhoat** [jpb06/jest-badges-action#29]
Hi,

I'm trying to generate a jest coverage badge with this action, and I'm using the following configuration:
```
    - name: Run tests with coverage
      run: npm run cover:ci
    - name: Generating coverage badges
      uses: jpb06/jest-badges-action@latest
      with:
        branches: main
        coverage-summary-path: dist/coverage/all/coverage-summary.json
```

The pipeline gives the following errors:

```
Run jpb06/jest-badges-action@latest
> Generating badges
generateBadges: badges generation failure: [Error: ENOENT: no such file or directory, open '/home/runner/work/api-backend/api-backend/coverage/coverage-summary.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/runner/work/api-backend/api-backend/coverage/coverage-summary.json'
}
> Pushing badges to the repo
/usr/bin/git config --global user.name openhoat
/usr/bin/git config --global user.email openhoat@users.noreply.github.com
/usr/bin/git add ./badges
/usr/bin/git commit -m Updating coverage badges
On branch main
Your branch is up to date with 'origin/main'.
nothing to commit, working tree clean
Error: Oh no! An error occured: The process '/usr/bin/git' failed with exit code [1](https://github.com/Adikteev/api-backend/runs/6990067780?check_suite_focus=true#step:9:1)
```

It seems that the `coverage-summary-path` in the action code has a wrong value.

Any help would be apreciated, thx.
