### ISSUE TITLE
Generate badges on protected branch

### ISSUE THREAD

**Issue by Maksim631** [jpb06/jest-badges-action#49]
Good day!

I'm trying to add this actions to my rep. As branches I specified my develop branch, which is marked as protected. So, one can commit in that branch only via creating PR. 

Is it possible to specify feature branches to generate badges, for example by passing regex? May be .yml file will like like this
`branches: feature-* `

Or may be add new property to specify bracnhes where action should not be run

**Comment by jpb06** [comment]
Hello!

Sadly I don't think it's possible to allow an action to push on a protected branch 😞 (See [feature request #13836](https://github.com/community/community/discussions/13836)). 
There is [workarounds](https://github.com/marketplace/actions/push-to-status-check-protected-branches) though, if you  are willing to take that route.

On the other hand, pushing badges on features branches is not ideal either since it will add noise for the reviewers. That is why this action is using whitelisting for branches.

---

A solution to answer your need could be to sync an unprotected branch to your `develop` branch and then run the action against it. The branch would thus only be used to store badges:

```yaml
name: Sync to develop branch and generate badges

on:
  push:
    branches:
      - develop

jobs:
  sync-and-generate-badges:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout badges branch
        run: git checkout badges

      - name: Rebase badges on master
        run: git merge origin/master

      - name: Push badges branch
        run: git push origin badges

      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@latest
          with:
            branches: badges
```

What do you think about it?
