### ISSUE TITLE
provided branch name is skipped or not read

### ISSUE THREAD

**Issue by mjmohammadi1** [jpb06/jest-badges-action#53]
Hey there, 
Thanks for your great work on building this action. I'm trying to use it to add coverage badges to my project, and getting the following error.

```
Error: 🔶 Unable to get current branch from github event.
🔶 Current branch does not belong to the branches allowed for badges generation, task dropped.
```
I'm not sure if this is because of my branch naming pattern, or something else.

This is how I'm using the action:
```
    - name: Generating coverage badges
      uses: jpb06/jest-badges-action@latest
      with:
        branches: chore/badges,main
```
I'd appreciate if you let me know how I can resolve this.
