### ISSUE TITLE
Accept multiple lines for coverage-summary-path

### ISSUE THREAD

**Issue by SirPhemmiey** [jpb06/jest-badges-action#62]
Hello, 

Thanks for this action. 

I am using this action in a monorepo workflow and i'd like to generate a badge for some specific apps in the monorepo. 

Instead of specifying an action multiple times for different projects as in :

```
- name: Generating app-1 coverage badges
        uses: jpb06/jest-badges-action@latest
        with:
          coverage-summary-path: apps/app-1/coverage/coverage-summary.json

- name: Generating app-2 coverage badges 
        uses: jpb06/jest-badges-action@latest
        with:
          coverage-summary-path: apps/app-2/coverage/coverage-summary.json

```

Can it not be possible like this:
```
- name: Generating coverage badges
        uses: jpb06/jest-badges-action@latest
        with:
          coverage-summary-path: |
                apps/app-1/coverage/coverage-summary.json
               apps/app-2/coverage/coverage-summary.json
```

Or probably pass a wildcard path to it like this:
```
- name: Generating coverage badges
        uses: jpb06/jest-badges-action@latest
        with:
          coverage-summary-path: |
                apps/**/coverage-summary.json
```

Looking forward for your response on this
