### ISSUE TITLE
feat: dynamic coverage summary path

### ISSUE THREAD

**Issue by Narixius** [jpb06/jest-badges-action#8]
Hi dear maintainer
Thanks for this great solution.

I am using this action on a monorepo project, so jest generates multiple coverage-summery files per package. I just wanted to suggest that is there a way to make coverageSummaryPath dynamic? then users can run this action multiple times for every coverage-summery file that is generated by jest.

I checked the path of the coverage-summary.json file and I found out that it is statically sat on the project.
https://github.com/jpb06/jest-badges-action/blob/43b8143fa6eff15cfabe7f765fbd3e200b64201a/src/logic/jest/isJestCoverageReportAvailable.ts#L11

Is there a way to make it dynamic, and let the user define this path on the action yml file?
like the code below
```
  - name: Generating coverage badges
    uses: jpb06/jest-badges-action@v1.6.0
    summery-path: packages/main/coverage/coverage-summary.json
    with:
      branches: master
``` 

Thanks for maintaining this project.
